#     *********************************************
#     *           中文名：ReSpawn                 *
#     *           作  者：Kouleen                 *
#     *           版  本：1.0.0                   *
#     *********************************************
death:
  # 是否在玩家死亡是保存背包 ?
  keepInventory: true
  # 是否在玩家死亡等级 ?
  keepLevel: true
  # 是否死亡扣除金币 ?
  enableDropMoney: true
  # 设置每次死亡扣减的金币数量 ,如果  isEnableDropMoney 设置为false，那这设置将不起任何作用
  dropMoney: 1000
  # 是否启动死完自定义播报
  enableBroadcastMessage: true
  # 设置多少等级不扣钱包含当前等级
  maxDropMoney: 30
  # 掉落等级的范围
  level-scope: 30
message:
  # 定义玩家扣除东西后发发送的消息
  1: '§e§l菜逼，30级都没，腐竹§a§l保住§e§l你的等级和金钱，但是没有保住你背包...'
  # 设置死亡自定义播报，如果 isEnableBroadcastMessage 设置为false，这将什么作用都木有
  2: '§e§l居然飞升成仙了，好家伙不等我'
  # 扣除金币后的消息
  3: '§4§l天空飞来一群鸭~呱！呱！！呱！！！噶！！！！'

