main: com.kouleen.respawn.Main

name: 'respawn'
version: '1.0.0'
api-version: '1.13'
website: https://files.gitee.com/group1/M00/1C/6A/CgAAEmDVNE2AVhkFAAAX-BRnAlw040.jar?token=7960c2cc5bc92b4c404edcd017d8e8d8&ts=1625992950&attname=ReSpawn-1.0.0.jar&disposition=attachment
authors:
  - 'Kouleen'
softdepend:
  - Vault
commands:
  respawn:
    description: '死亡随机掉落物品'
    usage: '帮助: /<command> help'
    permission: op
    permission-message: '你没有使用此命令的权限'