name: SupperMessage
version: '${project.version}'
main: com.kouleen.suppermessage.SupperMessage
authors: [ kouleen ]
description: supper message
commands:
  message:
    description: 'Admin commands'
    usage:  |
      /message help
